# Generated by Django 5.0.7 on 2024-07-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_function', models.DateField()),
                ('time_of_function', models.TimeField()),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('private_event', 'Private Event'), ('corporate_event', 'Corporate Event'), ('birthday_party', 'Birthday Party'), ('other', 'Other')], max_length=50)),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('estimated_guests', models.IntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
